"use client";
import {useState} from 'react';
import {trpc} from '@/lib/trpc/client';
import {PROCESSING_ROUTES,pakistanDate} from '@/lib/sesame-processing';
import {isSesameCommodity} from '@/lib/sesame';
import {useExecutionCommodityDesk} from './commodity-desk-provider';
import {SesameGradeStock} from './sesame-grade-stock';
const fmt=(v:number)=>v.toLocaleString('en-PK',{maximumFractionDigits:3});
const inputClass='kastros-input block w-full mt-1';
const cell='p-3 text-left whitespace-nowrap';
export function ProcessedGoods(){
 const {active,entity}=useExecutionCommodityDesk();
 if(!isSesameCommodity(active.code)||entity==='FZCO')return <p>Open the Pakistan Sesame desk to process goods.</p>;
 return <WarehouseProcessing key={active.code}/>;
}
function WarehouseProcessing(){
 const utils=trpc.useUtils();
 const query=trpc.sesameExecution.warehouseProcessing.useQuery(undefined,{refetchInterval:30000});
 const [warehouse,setWarehouse]=useState(''),[unit,setUnit]=useState('Processing unit'),[route,setRoute]=useState('0');
 const [reserved,setReserved]=useState(''),[capacity,setCapacity]=useState(''),[yieldPct,setYield]=useState('98');
 const [planId,setPlan]=useState(''),[date,setDate]=useState(()=>pakistanDate()),[output,setOutput]=useState(''),[impurities,setImpurities]=useState('');
 const [editCapacity,setEditCapacity]=useState(''),[editYield,setEditYield]=useState('');
 const [planKey,setPlanKey]=useState(()=>crypto.randomUUID()),[recordKey,setRecordKey]=useState(()=>crypto.randomUUID());
 const [message,setMessage]=useState('');
 const refresh=()=>{void utils.invalidate();};
 const create=trpc.sesameExecution.createProcessingPlan.useMutation({onSuccess:result=>{setPlan(result.id);setReserved('');setPlanKey(crypto.randomUUID());setMessage('Batch reserved. Enter actual daily output below.');refresh();}});
 const record=trpc.sesameExecution.recordProduction.useMutation({onSuccess:()=>{setOutput('');setImpurities('');setRecordKey(crypto.randomUUID());setMessage('Daily production saved and inventory updated.');refresh();}});
 const update=trpc.sesameExecution.updateProcessingPlan.useMutation({onSuccess:()=>{setEditCapacity('');setEditYield('');setMessage('Processing batch updated.');refresh();}});
 const conversion=PROCESSING_ROUTES[Number(route)]!;
 const wh=query.data?.warehouses.find(w=>w.name===warehouse);
 const availability=wh?.grades.find(g=>g.grade===conversion.from);
 const selected=query.data?.plans.find(p=>p.id===planId&&p.status==='ACTIVE');
 const input=Number(output)+Number(impurities);
 const error=query.error??create.error??record.error??update.error;
 const choose=(id:string)=>{setPlan(id);setOutput('');setImpurities('');setEditCapacity('');setEditYield('');setRecordKey(crypto.randomUUID());};
 function useDailyPlan(){if(!selected)return;const amount=Math.min(selected.dailyCapacityKg,selected.remainingKg);const out=Math.round(amount*selected.expectedYieldRatio*1000)/1000;setOutput(String(out));setImpurities(String(Math.round((amount-out)*1000)/1000));}
 return <div className="kastros-desk-page space-y-5"><h1 className="text-2xl font-semibold">Warehouse processing</h1><p className="text-sm text-subtle">Reserve unbooked physical stock for a warehouse processing unit. Record cleaned / Sortex output and impurities each day; their sum is the input consumed. Each saved entry updates inventory automatically.</p>
  <SesameGradeStock/>{query.isLoading&&<p>Loading warehouse availability…</p>}{error&&<p role="alert" className="text-destructive">{error.message}</p>}{message&&<p role="status">{message}</p>}
  <form className="kastros-card p-5 space-y-4" onSubmit={e=>{e.preventDefault();setMessage('');create.mutate({warehouseName:warehouse,unitName:unit,fromType:conversion.from,toType:conversion.to,reservedKg:Number(reserved),dailyCapacityKg:Number(capacity),expectedYieldRatio:Number(yieldPct)/100,requestKey:planKey});}}>
   <h2 className="font-semibold">Reserve a processing batch</h2><div className="grid gap-4 md:grid-cols-3">
    <label>Warehouse<select required className="kastros-select block w-full mt-1" value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">Select warehouse</option>{query.data?.warehouses.map(w=><option key={w.name}>{w.name}</option>)}</select></label>
    <label>Processing unit name<input required className={inputClass} value={unit} onChange={e=>setUnit(e.target.value)}/></label>
    <label>Conversion<select className="kastros-select block w-full mt-1" value={route} onChange={e=>setRoute(e.target.value)}>{PROCESSING_ROUTES.map((r,i)=><option key={i} value={i}>{r.from} → {r.to}</option>)}</select></label>
    <label>Quantity to reserve (kg)<input required className={inputClass} type="number" min="0.001" step="0.001" max={availability?.availableKg} value={reserved} onChange={e=>setReserved(e.target.value)}/></label>
    <label>Daily input capacity (kg)<input required className={inputClass} type="number" min="0.001" step="0.001" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label>
    <label>Initial expected yield (%)<input required className={inputClass} type="number" min="0" max="100" step="0.0001" value={yieldPct} onChange={e=>setYield(e.target.value)}/></label>
   </div>{availability&&<p className="text-sm">{conversion.from}: physical {fmt(availability.physicalKg)} kg · booked sales {fmt(availability.bookedKg)} kg · locked in processing {fmt(availability.processingKg)} kg · available {fmt(availability.availableKg)} kg.</p>}<button className="kastros-btn-primary" disabled={create.isPending||!warehouse}>Reserve stock</button>
  </form>
  <section className="kastros-card p-5 space-y-4"><h2 className="font-semibold">Daily production</h2><label>Active batch<select className="kastros-select block mt-1 w-full" value={planId} onChange={e=>choose(e.target.value)}><option value="">Select batch</option>{query.data?.plans.filter(p=>p.status==='ACTIVE').map(p=><option key={p.id} value={p.id}>{p.warehouseName} · {p.unitName} · {p.fromType} → {p.toType} · {fmt(p.remainingKg)} kg remaining · {p.id.slice(-6)}</option>)}</select></label>
   {selected&&<><form className="space-y-4" onSubmit={e=>{e.preventDefault();setMessage('');record.mutate({planId,productionDate:date,outputKg:Number(output),impuritiesKg:Number(impurities),requestKey:recordKey});}}><div className="grid gap-4 md:grid-cols-3"><label>Production date<input required type="date" className={inputClass} min={pakistanDate(new Date(selected.createdAt))} max={pakistanDate()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>{selected.toType} produced (kg)<input required type="number" min="0" step="0.001" className={inputClass} value={output} onChange={e=>setOutput(e.target.value)}/></label><label>Impurities (kg)<input required type="number" min="0" step="0.001" className={inputClass} value={impurities} onChange={e=>setImpurities(e.target.value)}/></label></div><p>Total input: <strong>{fmt(input)} kg</strong> · Yield: <strong>{input>0?(Number(output)/input*100).toFixed(2):'—'}%</strong> · Remaining reserved: {fmt(selected.remainingKg)} kg</p><div className="flex gap-3"><button type="button" className="kastros-btn-secondary" onClick={useDailyPlan}>Use daily capacity defaults</button><button className="kastros-btn-primary" disabled={record.isPending||input<=0||input>selected.remainingKg}>Save daily production</button></div><p className="text-xs text-subtle">You can record multiple runs on the same date. Defaults are editable; inventory changes only when actual production is saved.</p></form>
   <form className="border-t border-border pt-4 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();update.mutate({id:planId,dailyCapacityKg:Number(editCapacity||selected.dailyCapacityKg),expectedYieldRatio:Number(editYield||selected.expectedYieldRatio*100)/100});}}><label>Daily capacity (kg)<input className={inputClass} type="number" min="0.001" step="0.001" placeholder={String(selected.dailyCapacityKg)} value={editCapacity} onChange={e=>setEditCapacity(e.target.value)}/></label><label>Default yield (%)<input className={inputClass} type="number" min="0" max="100" step="0.0001" placeholder={String(selected.expectedYieldRatio*100)} value={editYield} onChange={e=>setEditYield(e.target.value)}/></label><button className="kastros-btn-secondary" disabled={update.isPending}>Update defaults</button><button type="button" className="kastros-btn-secondary" disabled={update.isPending} onClick={()=>{if(window.confirm('Release this batch’s remaining reservation? Completed production will stay in inventory.'))update.mutate({id:planId,cancel:true});}}>Release remaining reservation</button></form></>}
  </section>
  <section className="kastros-card p-5 overflow-auto"><h2 className="font-semibold mb-3">Batch progress and 3-month forecast (90 days)</h2><p className="text-xs text-subtle mb-3">Uses the last 90 days’ weighted yield and average input per calendar day since the first recorded production day, including idle days. Before production starts, uses planned capacity and yield. Forecast quantities are capped at the remaining batch stock.</p><table className="w-full text-sm"><thead><tr>{['Warehouse / unit','Conversion','Status','Reserved kg','Remaining kg','Average kg / day','Yield','Days to finish','90-day output kg','90-day impurities kg','Basis'].map(h=><th className={cell} key={h}>{h}</th>)}</tr></thead><tbody>{query.data?.plans.map(p=><tr className="border-t border-border" key={p.id}><td className={cell}>{p.warehouseName} · {p.unitName}<span className="block text-xs">{p.id.slice(-6)}</span></td><td className={cell}>{p.fromType} → {p.toType}</td><td className={cell}>{p.status}</td><td className={cell}>{fmt(p.reservedKg)}</td><td className={cell}>{p.status==='CANCELLED'?'Released':fmt(p.remainingKg)}</td><td className={cell}>{fmt(p.forecast.dailyKg)}</td><td className={cell}>{(p.forecast.yieldRatio*100).toFixed(2)}%</td><td className={cell}>{p.status==='ACTIVE'?p.forecast.daysRemaining??'—':'—'}</td><td className={cell}>{fmt(p.forecast.forecastOutputKg)}</td><td className={cell}>{fmt(p.forecast.forecastImpuritiesKg)}</td><td className={cell}>{p.forecast.basis}</td></tr>)}</tbody></table></section>
  <section className="kastros-card p-5 overflow-auto"><h2 className="font-semibold mb-3">Daily totals by warehouse and conversion</h2><table className="w-full text-sm"><thead><tr>{['Date','Warehouse','Conversion','Input kg','Output kg','Impurities kg','Yield'].map(h=><th className={cell} key={h}>{h}</th>)}</tr></thead><tbody>{query.data?.daily.map(r=><tr className="border-t border-border" key={[r.date,r.warehouseName,r.fromType,r.toType].join(':')}><td className={cell}>{r.date}</td><td className={cell}>{r.warehouseName}</td><td className={cell}>{r.fromType} → {r.toType}</td><td className={cell}>{fmt(r.inputKg)}</td><td className={cell}>{fmt(r.outputKg)}</td><td className={cell}>{fmt(r.impuritiesKg)}</td><td className={cell}>{r.inputKg>0?(r.outputKg/r.inputKg*100).toFixed(2):'—'}%</td></tr>)}</tbody></table></section>
  <section className="kastros-card p-5 overflow-auto"><h2 className="font-semibold mb-3">Daily production history</h2><table className="w-full text-sm"><thead><tr>{['Date','Warehouse','Conversion','Input kg','Output kg','Impurities kg','Yield','Recorded by'].map(h=><th className={cell} key={h}>{h}</th>)}</tr></thead><tbody>{query.data?.history.map(r=><tr className="border-t border-border" key={r.id}><td className={cell}>{r.productionDate??pakistanDate(new Date(r.createdAt))}</td><td className={cell}>{r.warehouseName}</td><td className={cell}>{r.fromType} → {r.toType}</td><td className={cell}>{fmt(r.inputKg)}</td><td className={cell}>{fmt(r.outputKg)}</td><td className={cell}>{fmt(r.impuritiesKg)}</td><td className={cell}>{(r.yieldRatio*100).toFixed(2)}%</td><td className={cell}>{r.recordedBy}</td></tr>)}</tbody></table></section>
 </div>;
}
