/** Empty local disposable database only. */
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {prisma} from '../server/db';
import {appRouter} from '../server/routers/_app';
import {assignCommodityTrader} from '../server/commodity-assignments';
import {SESAME_DEFAULTS} from '../lib/sesame';
import {createProcessingPlan,recordWarehouseProduction,warehouseProcessing,processingAvailability,updateProcessingPlan} from '../server/execution/warehouse-processing';
import {sesameGrades,assertGradeAvailable} from '../server/execution/sesame-processing';
import {pakistanAvailable} from '../server/execution/sesame-stock';
import {pakistanDate} from '../lib/sesame-processing';
import {supplierEntryType,purchasePaidTotal} from '../lib/purchase-ledger-display';
async function main(){
 const url=new URL(process.env.POSTGRES_PRISMA_URL!);assert.ok(['localhost','127.0.0.1'].includes(url.hostname)&&url.port==='55433');assert.equal(await prisma.user.count(),0);
 const admin=await prisma.user.create({data:{email:'admin@example.invalid',name:'Admin',role:'CEO',passwordHash:'test'}});
 const trader=await prisma.user.create({data:{email:'trader@example.invalid',name:'Test Trader',role:'TRADER',passwordHash:'test'}});
 const other=await prisma.user.create({data:{email:'other@example.invalid',name:'Corn Trader',role:'TRADER',passwordHash:'test'}});
 const ses=await prisma.commodity.create({data:{code:'SES',name:'Sesame',category:'OILSEEDS',unit:'MT',createdById:admin.id}});
 const corn=await prisma.commodity.create({data:{code:'CORN',name:'Corn',category:'GRAINS',unit:'MT',createdById:admin.id}});
 await assignCommodityTrader({commodityId:ses.id,traderId:trader.id,expectedVersion:0,actorId:admin.id});await assignCommodityTrader({commodityId:corn.id,traderId:other.id,expectedVersion:0,actorId:admin.id});
 const cp=await prisma.counterparty.create({data:{code:'CP',name:'Test',country:'Pakistan',type:'TRADING_PARTNER',createdById:admin.id}});
 for(const name of ['Test WH','Other WH','Faqir Warehouse'])await prisma.location.create({data:{name,country:'Pakistan',type:'WAREHOUSE',warehouseBasis:'USE',createdById:admin.id}});
 const caller=(u=trader,code?:string)=>appRouter.createCaller({prisma,executionCommodityCode:code,executionEntity:'PAK',session:{user:{id:u.id,name:u.name,email:u.email,role:u.role,isHead:u.isHead},expires:'2099-01-01'}});
 const book=(direction:'BUY'|'SELL',qty:number,unit='MT',warehouse='Test WH')=>caller().trader.bookTrade({commodityId:ses.id,counterpartyId:cp.id,traderName:trader.name!,direction,quantity:qty,quantityUnit:'MT',price:11000,priceCurrency:'PKR',priceWeightUnit:unit,priceKgPerUnit:1000,priceIncludesCommission:true,commissionPerUnit:5,priceBasis:'Fixed',tradeDate:new Date(),deliveryStart:new Date(),deliveryEnd:new Date(),originName:'Karachi',incoterms:direction==='BUY'?'Delivered':'Ex-Warehouse',paymentType:'ADVANCE_100',tradeScope:'LOCAL',tradeParams:{...SESAME_DEFAULTS,sesameType:'Raw',warehouseSelections:warehouse,paymentPercentage:80}});
 const purchase=await book('BUY',1000,'MAUND_40');const saved=await prisma.trade.findUniqueOrThrow({where:{tradeRef:purchase.tradeRef}});assert.equal(Number(saved.pricePerCanonicalQty),274875);assert.equal(saved.paymentTerms,'80% Advance');
 await assert.rejects(()=>book('BUY',1,'MT','Faqir Warehouse'),/Faqir/);
 for(const [name,qty] of [['Test WH',200],['Other WH',100]] as const)await prisma.stockTransfer.create({data:{transferRef:randomUUID(),commodityCode:'SES',commodityName:'Sesame',sesameType:'Raw',externalOrigin:'Opening stock',toWarehouseName:name,dispatchedQtyMt:qty,receivedQtyMt:qty,truckNo:'OPENING',status:'RECEIVED'}});
 await book('SELL',50);
 const base={warehouseName:'Test WH',unitName:'Machine 1',fromType:'Raw' as const,toType:'Machine Cleaned' as const,reservedKg:50000,dailyCapacityKg:5000,expectedYieldRatio:.8,requestKey:randomUUID()};
 const plan=await createProcessingPlan('SES','Admin',base);assert.deepEqual(await createProcessingPlan('SES','Admin',base),plan);
 assert.equal((await processingAvailability(prisma,'SES','Test WH','Raw')).availableKg,100000);
 await assert.rejects(()=>createProcessingPlan('SES','Admin',{...base,reservedKg:100001,requestKey:randomUUID()}),/Only/);
 await assert.rejects(()=>book('SELL',101),/processing/);
 await assert.rejects(()=>assertGradeAvailable(prisma,'SES','Test WH','Raw',151),/Insufficient/);
 assert.equal(await pakistanAvailable(prisma,'SES','Test WH'),150);
 const daily={planId:plan.id,productionDate:pakistanDate(),outputKg:4000,impuritiesKg:1000,requestKey:randomUUID()};
 const rec=await recordWarehouseProduction('SES','Admin',daily);assert.deepEqual(await recordWarehouseProduction('SES','Admin',daily),rec);
 await assert.rejects(()=>recordWarehouseProduction('SES','Admin',{...daily,outputKg:50000,requestKey:randomUUID()}),/remaining/);
 await assert.rejects(()=>recordWarehouseProduction('SES','Admin',{...daily,productionDate:'2099-01-01',requestKey:randomUUID()}),/date/);
 await assert.rejects(()=>recordWarehouseProduction('CORN','Admin',{...daily,requestKey:randomUUID()}),/desk/);
 let stock=(await sesameGrades(prisma,'SES')).find(w=>w.name==='Test WH')!;assert.equal(stock.grades.Raw,195);assert.equal(stock.grades['Machine Cleaned'],4);assert.equal(stock.grades.Impurities,1);assert.equal(stock.sesameStockMt,200);
 const view=await warehouseProcessing('SES');assert.ok(!view.warehouses.some(w=>w.name==='Faqir Warehouse'));const forecast=view.plans.find(p=>p.id===plan.id)!.forecast;assert.equal(forecast.daysRemaining,9);assert.equal(forecast.forecastOutputKg,36000);assert.ok(Math.abs(forecast.forecastImpuritiesKg-9000)<.0001);
 const next=await createProcessingPlan('SES','Admin',{...base,fromType:'Machine Cleaned',toType:'Sortex',reservedKg:4000,requestKey:randomUUID()});await recordWarehouseProduction('SES','Admin',{...daily,planId:next.id,outputKg:3900,impuritiesKg:100,requestKey:randomUUID()});
 stock=(await sesameGrades(prisma,'SES')).find(w=>w.name==='Test WH')!;assert.equal(stock.grades['Machine Cleaned'],0);assert.equal(stock.grades.Sortex,3.9);assert.equal(stock.grades.Impurities,1.1);assert.equal(stock.sesameStockMt,200);
 const rawSortex=await createProcessingPlan('SES','Admin',{...base,toType:'Sortex',reservedKg:5000,requestKey:randomUUID()});await recordWarehouseProduction('SES','Admin',{...daily,planId:rawSortex.id,outputKg:4500,impuritiesKg:500,requestKey:randomUUID()});
 await updateProcessingPlan('SES',{id:plan.id,dailyCapacityKg:6000});assert.equal(Number((await prisma.sesameProcessingPlan.findUniqueOrThrow({where:{id:plan.id}})).dailyCapacityKg),6000);
 await updateProcessingPlan('SES',{id:plan.id,cancel:true});assert.equal(await pakistanAvailable(prisma,'SES','Test WH'),200);
 const attempts=await Promise.allSettled([1,2].map(()=>createProcessingPlan('SES','Admin',{...base,warehouseName:'Other WH',reservedKg:80000,requestKey:randomUUID()})));assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);
 assert.equal((await caller(other).sesameExecution.positionSnapshot({commodityCode:'SES'})).positions.length,2);await assert.rejects(()=>caller(other).sesameExecution.book({commodityCode:'SES'}));await assert.rejects(()=>caller(other).trader.setPositionMarketInput({commodityCode:'SES',season:'SUMMER',fxRate:280}));assert.equal((await caller().trader.positionCommodities()).length,2);
 const entries=[{entryType:'CREDIT' as const,purchaseAdvanceFlow:true,amountPkr:1759200},{entryType:'DEBIT' as const,purchaseAdvanceFlow:true,amountPkr:2194602},{entryType:'CREDIT' as const,purchaseAdvanceFlow:true,amountPkr:435402}];assert.equal(purchasePaidTotal(entries),2194602);assert.deepEqual(entries.map(e=>supplierEntryType('BUY',e)),['DEBIT','CREDIT','DEBIT']);assert.equal(supplierEntryType('SELL',entries[0]),'CREDIT');
 console.log('PASS: Maund price/commission, payment terms, Faqir exclusion, sales and processing reservations, all three routes, daily quantities/yield, forecasts, retries, cross-desk access, ledger labels');
}
main().finally(()=>prisma.$disconnect());
