/** Run only against an empty disposable local database on port 55433. */
import assert from 'node:assert/strict';
import bcrypt from 'bcryptjs';
import { prisma } from '../server/db';
import { appRouter } from '../server/routers/_app';
import { assignCommodityTrader } from '../server/commodity-assignments';
import { SESAME_DEFAULTS } from '../lib/sesame';
import { approveVoucher } from '../server/finance/vouchers';
import { canFundTruck } from '../server/finance/ledger';

async function main() {
 const url = new URL(process.env.POSTGRES_PRISMA_URL ?? 'http://invalid');
 assert.ok(['localhost','127.0.0.1'].includes(url.hostname) && url.port === '55433');
 assert.equal(await prisma.user.count(), 0, 'Only an empty test database is allowed');
 const passwordHash = await bcrypt.hash('LocalTest123!',4);
 const admin=await prisma.user.create({data:{email:'admin@example.test',name:'Admin',role:'ADMIN',passwordHash}});
 const ceo=await prisma.user.create({data:{email:'ceo@example.test',name:'CEO',role:'CEO',passwordHash}});
 const employee=await prisma.user.create({data:{email:'execution@example.test',name:'Execution Member',role:'EXECUTION',passwordHash}});
 const colleague=await prisma.user.create({data:{email:'execution2@example.test',name:'Execution Colleague',role:'EXECUTION',passwordHash}});
 const trader=await prisma.user.create({data:{email:'trader@example.test',name:'Test Trader',role:'TRADER',passwordHash}});
 const corn=await prisma.commodity.create({data:{code:'CORN',name:'Corn',category:'GRAINS',unit:'MT',createdById:admin.id}});
 const sesame=await prisma.commodity.create({data:{code:'SES',name:'Sesame',category:'OILSEEDS',unit:'MT',createdById:admin.id}});
 const cp=await prisma.counterparty.create({data:{code:'CP-TEST',name:'Shared Counterparty',country:'Pakistan',type:'TRADING_PARTNER',createdById:admin.id}});
 for(const commodityId of [corn.id,sesame.id]) await assignCommodityTrader({commodityId,traderId:trader.id,expectedVersion:0,actorId:ceo.id});
 const caller=(user=employee,code?:string)=>appRouter.createCaller({prisma,executionCommodityCode:code,session:{user:{id:user.id,name:user.name,email:user.email,role:user.role,isHead:user.isHead},expires:'2099-01-01'}});
 const c=caller(employee,'CORN'),s=caller(employee,'SES'),ch=caller(admin,'CORN'),sh=caller(admin,'SES');
 for(const u of [employee,colleague]) assert.deepEqual((await caller(u).execution.commodityDesks()).map(d=>d.code),['CORN','SES']);
 const book=async(code:string,direction:'BUY'|'SELL')=>caller(trader).trader.bookTrade({traderName:trader.name!,commodityId:code==='SES'?sesame.id:corn.id,counterpartyId:cp.id,direction,quantity:10,quantityUnit:'MT',price:code==='SES'?1200:1000,priceIncludesCommission:code==='SES',commissionPerUnit:code==='SES'?10:0,priceCurrency:code==='SES'?'USD':'PKR',priceWeightUnit:'MT',priceKgPerUnit:1000,priceBasis:'Fixed',tradeDate:new Date(),deliveryStart:new Date(),deliveryEnd:new Date(),originName:'Karachi',incoterms:'Delivered',paymentType:'LC',tradeScope:'LOCAL',tradeParams:code==='SES'?{...SESAME_DEFAULTS}:{},submitToExecution:true});
 const cb=await book('CORN','BUY'),sb=await book('SES','BUY'),cs=await book('CORN','SELL'),ss=await book('SES','SELL');
 assert.equal((await c.execution.openTrades()).length,2);assert.equal((await s.execution.openTrades()).length,2);
 assert.ok((await s.execution.openTrades()).every(t=>t.commodityCode==='SES'));assert.equal((await s.execution.deskSummary()).openTrades,2);
 await assert.rejects(()=>s.execution.openTradeByRef({tradeRef:cb.tradeRef}),/another commodity/);
 await assert.rejects(()=>s.execution.approveOpenTradeWarehouseSplit({tradeRef:sb.tradeRef,allocations:[{warehouseName:'Test Warehouse',openQtyMt:10}]}),/Head/);
 for(const [head,t] of [[sh,sb],[sh,ss],[ch,cb],[ch,cs]] as const) await head.execution.approveOpenTradeWarehouseSplit({tradeRef:t.tradeRef,allocations:[{warehouseName:'Test Warehouse',openQtyMt:10}]});
 await assert.rejects(()=>s.execution.lockOpenTrade({tradeRef:sb.tradeRef}),/USD\/PKR/);
 await s.trader.setPositionMarketInput({commodityCode:'SES',season:'SUMMER',fxRate:280});
 for(const [api,t] of [[s,sb],[s,ss],[c,cb],[c,cs]] as const) await api.execution.lockOpenTrade({tradeRef:t.tradeRef});
 assert.equal((await s.execution.contractByRef({tradeRef:sb.tradeRef})).contract.ratePerKg,333.2);
 assert.equal((await c.execution.contractByRef({tradeRef:cb.tradeRef})).contract.ratePerKg,1);
 await s.trader.setPositionMarketInput({commodityCode:'SES',season:'SUMMER',fxRate:300});
 assert.equal((await s.execution.contractByRef({tradeRef:sb.tradeRef})).contract.ratePerKg,333.2);
 assert.equal((await s.execution.gateInvoiceSummary({tradeRef:sb.tradeRef})).totalTradeValuePkr,3360000);
 const createTruck=(movementType:'INBOUND'|'OUTBOUND',weight:number)=>s.execution.createPendingTruck({counterpartyName:cp.name,movementType,warehouseName:'Test Warehouse',truckNo:'SES-'+movementType,builtyDetails:'Test',commodityCode:'SES',commodityName:'Sesame',recordedByName:employee.name!,weightAsPerBuiltyKg:weight,warehouseWeightKg:weight,totalDeductionsKg:0});
 const truck=await createTruck('INBOUND',1000);
 assert.equal((await c.execution.pendingTrucks()).length,0);
 await assert.rejects(()=>ch.execution.deleteGateEntry({id:truck.id}),/another commodity/);
 await s.execution.assignTruckToTrade({truckId:truck.id,tradeRef:sb.tradeRef});
 assert.equal((await s.execution.inboundReceipts()).length,1);assert.equal((await c.execution.inboundReceipts()).length,0);
 assert.equal((await s.execution.inventoryValuation()).totalPurchasedMt,1);
 assert.ok(Math.abs((await s.execution.inventoryValuation()).weightedPurchasePricePkrPerMt-333200)<0.01);
 assert.equal((await c.execution.inventoryValuation()).totalPurchasedMt,0);
 const cv=await c.execution.createVoucher({counterpartyId:cp.id,amountPkr:1000000,method:'Cash',reference:'CORN-CREDIT'});await approveVoucher(cv.id,'Test Finance');
 assert.equal((await c.execution.counterpartyLedgers()).find(a=>a.side==='SELL')?.availableCreditPkr,1000000);
 assert.ok(!(await s.execution.counterpartyLedgers()).some(a=>a.side==='SELL'&&a.totalCreditPkr>0));
 assert.equal((await canFundTruck({counterpartyId:cp.id,tradeRef:ss.tradeRef,amountPkr:100})).ok,false);
 const sv=await s.execution.createVoucher({counterpartyId:cp.id,amountPkr:500000,method:'Cash',reference:'SES-CREDIT'});await approveVoucher(sv.id,'Test Finance');
 assert.equal((await s.execution.counterpartyLedgers()).find(a=>a.side==='SELL')?.availableCreditPkr,500000);
 assert.equal((await c.execution.counterpartyLedgers()).find(a=>a.side==='SELL')?.availableCreditPkr,1000000);
 assert.equal((await caller(admin).execution.counterpartyLedgers()).find(a=>a.side==='SELL')?.totalCreditPkr,1500000);
 assert.equal((await s.execution.vouchers()).length,1);assert.equal((await c.execution.vouchers()).length,1);
 await assert.rejects(()=>s.execution.createVoucher({counterpartyId:cp.id,tradeRef:cs.tradeRef,amountPkr:100,reference:'WRONG-DESK'}),/another commodity/);
 if (process.env.EXECUTION_TEST_SKIP_OUTBOUND !== '1') {
 const out=await createTruck('OUTBOUND',500);await s.execution.assignTruckToTrade({truckId:out.id,tradeRef:ss.tradeRef});
 await s.execution.generateDeliveryOrder({truckId:out.id});
 assert.equal((await s.execution.doExecutionApprovals()).length,1);assert.equal((await c.execution.doExecutionApprovals()).length,0);
 await sh.execution.approveDoExecution({truckId:out.id});await caller(admin).execution.approveDoFinance({truckId:out.id});
 await s.execution.generateGatePass({truckId:out.id});await s.execution.markSaleReleased({truckId:out.id});
 assert.equal((await s.execution.outboundDispatches()).length,1);assert.equal((await c.execution.outboundDispatches()).length,0);
 assert.equal((await s.execution.inventoryValuation()).totalSoldMt,0.5);
 }
 const csv=await s.execution.exportTradeFileCsv({});assert.ok(csv.csv.includes(sb.tradeRef)&&!csv.csv.includes(cb.tradeRef));
 assert.ok((await s.execution.tradeFileOptions()).commodities.every(x=>x.code==='SES'));
 assert.ok((await s.trader.seasonNetPositions()).every(x=>x.commodityCode==='SES'));
 assert.equal((await caller(colleague,'SES').execution.lockedContracts()).length,2);
 await book('SES','BUY');await book('CORN','BUY');
 console.log('PASS: employee access, queues, ledger isolation, no cross-commodity funding, FX snapshot, inbound assignment, inventory and exports');
 console.log(process.env.EXECUTION_TEST_SKIP_OUTBOUND === '1' ? 'SKIPPED: outbound lifecycle (requires a PostgreSQL server with independent transactions)' : 'PASS: outbound assignment, DO approvals, gate pass and release');
}
main().finally(()=>prisma.$disconnect()).catch(error=>{console.error(error);process.exitCode=1;});
