import { recordTruckQuality } from "../server/execution/quality-review";
/** Integration check: an EMPTY, disposable local database on port 55433 only. */
import assert from "node:assert/strict";
import bcrypt from "bcryptjs";
import { prisma } from "../server/db";
import { appRouter } from "../server/routers/_app";
import { assignCommodityTrader } from "../server/commodity-assignments";
import { SESAME_DEFAULTS } from "../lib/sesame";
import { createVoucher, listVouchers, resolveExcessAdvance, excessAdvanceQueue, approveVoucher as approveVoucherImpl } from "../server/finance/vouchers";
import { canFundTruck } from "../server/finance/ledger";
import { pakistanAvailable } from "../server/execution/sesame-stock";

import { createPendingTruck, assignTruckToTrade, setManualGateInvoice, traderResolveGateInvoice } from "../server/execution/trucks";
import { approvePayment } from "../server/execution/payments";
import { applyAdvance, advanceTrade } from "../server/finance/purchase-advances";
import { getCounterpartyLedgers } from "../server/finance/ledger";
import { advanceAmount } from "../lib/purchase-advance";
const approveVoucher = (id:string, actor:string, note?:string, reference?:string) => approveVoucherImpl(id, actor, note, reference, {method:"Cash"});
async function main() {
  const url = new URL(process.env.POSTGRES_PRISMA_URL ?? "http://invalid");
  assert.ok(["localhost", "127.0.0.1"].includes(url.hostname) && url.port === "55433");
  assert.equal(await prisma.user.count(), 0, "Only an empty disposable database is allowed");
  const passwordHash = await bcrypt.hash("LocalTest123!", 4);
  const admin = await prisma.user.create({ data: { email: "admin@example.test", name: "Admin", role: "CEO", passwordHash } });
  const employee = await prisma.user.create({ data: { email: "execution@example.test", name: "Execution Member", role: "EXECUTION", passwordHash } });
  const trader = await prisma.user.create({ data: { email: "trader@example.test", name: "Test Trader", role: "TRADER", passwordHash } });
  const sesame = await prisma.commodity.create({ data: { code: "SES", name: "Sesame", category: "OILSEEDS", unit: "MT", createdById: admin.id } });
  await prisma.commodity.create({ data: { code: "CORN", name: "Corn", category: "GRAINS", unit: "MT", createdById: admin.id } });
  const cp = await prisma.counterparty.create({ data: { code: "CP-TEST", name: "Test Counterparty", country: "Pakistan", type: "TRADING_PARTNER", createdById: admin.id } });
  await assignCommodityTrader({ commodityId: sesame.id, traderId: trader.id, expectedVersion: 0, actorId: admin.id });
  const caller = (user = employee, code?: string, entity?: "PAK" | "FZCO") => appRouter.createCaller({ prisma, executionCommodityCode: code, executionEntity: entity, session: { user: { id: user.id, name: user.name, email: user.email, role: user.role, isHead: user.isHead }, expires: "2099-01-01" } });
  const pak = caller(employee, "SES", "PAK"), dubai = caller(employee, "SES", "FZCO"), head = caller(admin, "SES", "PAK"), dh = caller(admin, "SES", "FZCO");
  const book = async (direction: "BUY" | "SELL", entity: "PAK" | "FZCO", quantity: number, internal?: "PAK" | "FZCO") => caller(trader).trader.bookTrade({
    traderName: trader.name!, commodityId: sesame.id, counterpartyId: cp.id, direction, quantity, quantityUnit: "MT", price: 1200, priceIncludesCommission: true, commissionPerUnit: 10, priceCurrency: "USD", priceWeightUnit: "MT", priceKgPerUnit: 1000, priceBasis: "Fixed", tradeDate: new Date(), deliveryStart: new Date(), deliveryEnd: new Date(), originName: "Karachi", incoterms: "Delivered", paymentType: "ADVANCE_100", tradeScope: "LOCAL", tradeParams: { ...SESAME_DEFAULTS, paymentPercentage: 80, tradingEntity: entity === "FZCO" ? "Kastros FZCO" : "Kastros PAK", ...(internal ? { internalCounterpartyEntity: internal } : {}) }, submitToExecution: true,
  });
  await pak.trader.setPositionMarketInput({ commodityCode: "SES", season: "SUMMER", fxRate: 280, marketRatePkrPerMaund: 14000 });
  const purchase = await book("BUY", "PAK", 100);
  await head.execution.approveOpenTradeWarehouseSplit({ tradeRef: purchase.tradeRef, allocations: [{ warehouseName: "Pakistan Store", openQtyMt: 100 }] });
  await pak.execution.lockOpenTrade({ tradeRef: purchase.tradeRef });
  const terms = await advanceTrade(purchase.tradeRef);
  const voucher = async (builty: string, amount: number, weight = 40000) => createVoucher({ executionEntity: "PAK", commodityCode: "SES", counterpartyId: cp.id, side: "BUY", tradeRef: purchase.tradeRef, builtyNumber: builty, truckNo: `TRUCK-${builty}`, transporterName: "Test Transport", advanceWeightKg: weight, amountPkr: amount,  method: "Cash", enteredByName: "Execution" });
  const gate = async (v: Awaited<ReturnType<typeof voucher>>, builty: string, received: number) => createPendingTruck({ counterpartyName: cp.name, movementType: "INBOUND", warehouseName: "Pakistan Store", truckNo: `TRUCK-${builty}`, builtyDetails: builty, commodityCode: "SES", commodityName: "Sesame", recordedByName: "Gate", weightKg: received, warehouseWeightKg: received, advanceVoucherId: v.id, advanceTradeRef: purchase.tradeRef });
  const first = await voucher("1001", advanceAmount(40000, terms.rateKg, 80));
  assert.equal(first.reference,null); assert.equal(first.method,null); assert.equal(first.bankName,null);
  await assert.rejects(approveVoucherImpl(first.id,"Finance",undefined,"REF"),/payment method/);
  await assert.rejects(approveVoucherImpl(first.id,"Finance",undefined,"REF",{method:"Bank transfer"}),/bank/);
  assert.equal(first.advancePercentage,80); assert.equal(first.calculatedAdvancePkr,first.amountPkr);
  await assert.rejects(gate(first,"1001",35000),/unused approved/);
  await assert.rejects(approveVoucher(first.id,"Finance"),/payment reference/);
  await approveVoucher(first.id,"Finance",undefined,"BANK-1001");
  await assert.rejects(approveVoucher(first.id,"Finance"),/already resolved/);
  await assert.rejects(voucher("1001",500),/active advance/);
  const truck=await gate(first,"1001",35000);
  await assert.rejects(gate(first,"1001",35000),/unused approved/);
  await assignTruckToTrade(truck.id,purchase.tradeRef);
  const unreviewed=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:truck.gatepassNo}});
  assert.equal(Number(unreviewed.allocatedQtyMt),35);assert.equal(Number(unreviewed.amountDue),0);
  assert.equal(await prisma.counterpartyLedgerEntry.count({where:{truckId:truck.id}}),0);
  await recordTruckQuality({truckId:truck.id,tradeRef:purchase.tradeRef,readings:{purity:"99",ffa:"2",moisture:"7",oilContent:"49",admixture:"1"},deductionKg:1000},"Lab","SES","PAK");
  const receipt=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:truck.gatepassNo}});
  assert.equal(Number(receipt.allocatedQtyMt),35);
  assert.equal(Number(receipt.amountDue),34000*terms.rateKg);
  await assert.rejects(setManualGateInvoice(truck.id,{invoiceNo:"MANUAL",amountPkr:1}),/Quality and Invoice/);
  await assert.rejects(recordTruckQuality({truckId:truck.id,tradeRef:purchase.tradeRef,readings:{},deductionKg:0},"Lab","SES","PAK"),/only be generated once/);
  await traderResolveGateInvoice(trader.name!,truck.id,"PARTIAL",{amountPkr:1000});
  const payment=await prisma.paymentRequest.findFirstOrThrow({where:{sourceId:receipt.id,status:"PENDING"}});
  assert.equal(Number(payment.amount),1000);
  assert.equal(payment.builtyNumber,"1001");assert.equal(payment.invoiceNumber,`INV-${truck.gatepassNo}`);assert.equal(Number(payment.remainingPercentage),20);
  await assert.rejects(approvePayment(payment.requestRef,"Finance"),/payment slip reference/);
  await approvePayment(payment.requestRef,"Finance",undefined,"FINAL-1001");
  await assert.rejects(approvePayment(payment.requestRef,"Finance",undefined,"FINAL-1001"),/Cannot approve/);
  await traderResolveGateInvoice(trader.name!,truck.id,"APPROVE");
  const remainder=await prisma.paymentRequest.findFirstOrThrow({where:{sourceId:receipt.id,status:"PENDING"}});
  assert.equal(Number(remainder.amount),Number(receipt.amountDue)-first.amountPkr-1000);
  await approvePayment(remainder.requestRef,"Finance",undefined,"FINAL-1001-BALANCE");
  const settled=(await listVouchers()).find(v=>v.id===first.id)!;
  assert.equal(settled.truckPaid,true);assert.equal(settled.availableAdvancePkr,0);
  const ledger=(await getCounterpartyLedgers("SES","PAK")).find(a=>a.counterpartyId===cp.id&&a.side==="BUY")!;
  assert.equal(ledger.totalCreditPkr,Number(receipt.amountDue));assert.equal(ledger.balancePkr,0);
  assert.equal(ledger.entries.filter(e=>e.entryType==="CREDIT").length,3);
  console.log("PASS: advance, short receipt, deduction, remaining finance payment, ledger credits, paid badge, retries");
  await prisma.trade.update({ where: { tradeRef: purchase.tradeRef }, data: { tradeParams: { ...SESAME_DEFAULTS, tradingEntity: "Kastros PAK", paymentPercentage: 90 } } });
  const over=await voucher("1002",10000,40);
  assert.equal(over.advancePercentage,90);
  assert.equal((await listVouchers()).find(v => v.id === first.id)!.advancePercentage,80);
  assert.notEqual(over.amountPkr,over.calculatedAdvancePkr);
  await approveVoucher(over.id,"Finance",undefined,"BANK-1002");
  const short=await gate(over,"1002",35);
  await assignTruckToTrade(short.id,purchase.tradeRef);
  await recordTruckQuality({truckId:short.id,tradeRef:purchase.tradeRef,readings:{purity:"99",ffa:"2",moisture:"7",oilContent:"49",admixture:"1"},deductionKg:5},"Lab","SES","PAK");
  const shortReceipt=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:short.gatepassNo}});

  await traderResolveGateInvoice(trader.name!,short.id,"APPROVE");
  const excess=(await listVouchers()).find(v=>v.id===over.id)!;
  assert.equal(excess.truckPaid,true);assert.ok(excess.availableAdvancePkr>0);
  assert.equal(await prisma.paymentRequest.count({where:{sourceId:shortReceipt.id}}),0);
  const next=await createPendingTruck({counterpartyName:cp.name,movementType:"INBOUND",warehouseName:"Pakistan Store",truckNo:"FUTURE",builtyDetails:"1003",commodityCode:"SES",commodityName:"Sesame",recordedByName:"Gate",weightKg:1000,warehouseWeightKg:1000});
  await assignTruckToTrade(next.id,purchase.tradeRef);
  await recordTruckQuality({truckId:next.id,tradeRef:purchase.tradeRef,readings:{purity:"99",ffa:"2",moisture:"7",oilContent:"49",admixture:"1"},deductionKg:0},"Lab","SES","PAK");
  const nextReceipt=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:next.gatepassNo}});

  await assert.rejects(prisma.$transaction(tx=>applyAdvance(tx,over.id,next.id,"Execution",excess.availableAdvancePkr+1)),/exceeds/);
  await assert.rejects(prisma.$transaction(async tx => {
    await tx.trade.update({ where: { tradeRef: purchase.tradeRef }, data: { tradeParams: { ...SESAME_DEFAULTS, tradingEntity: "Kastros FZCO" } } });
    await applyAdvance(tx,over.id,next.id,"Execution",1);
  }), /same supplier, commodity and entity/);
  await prisma.$transaction(tx=>applyAdvance(tx,over.id,next.id,"Execution",excess.availableAdvancePkr));
  await assert.rejects(prisma.$transaction(tx=>applyAdvance(tx,over.id,next.id,"Execution",1)),/exceeds/);
  assert.equal((await listVouchers()).find(v=>v.id===over.id)!.availableAdvancePkr,0);
  await traderResolveGateInvoice(trader.name!,next.id,"APPROVE");
  const nextPayment=await prisma.paymentRequest.findFirstOrThrow({where:{sourceId:nextReceipt.id,status:"PENDING"}});
  await approvePayment(nextPayment.requestRef,"Finance",undefined,"FINAL-1003");
  const finalLedger=(await getCounterpartyLedgers("SES","PAK")).find(a=>a.counterpartyId===cp.id&&a.side==="BUY")!;
  assert.equal(finalLedger.balancePkr,0);assert.equal(finalLedger.outstandingDebitPkr,0);
  console.log("PASS: manual override, excess credit, future truck allocation, overspend protection, no duplicate credit");
  const high=await createVoucher({executionEntity:"PAK",commodityCode:"SES",counterpartyId:cp.id,side:"BUY",tradeRef:purchase.tradeRef,builtyNumber:"1999",truckNo:"HIGH",transporterName:"Carrier",advanceWeightKg:100,advancePercentage:95,amountPkr:1000,enteredByName:"Execution"});
  assert.equal(high.traderApprovalRequired,true);assert.equal(high.agreedAdvancePercentage,90);
  assert.ok((await excessAdvanceQueue(trader.name!)).some(v=>v.id===high.id));
  assert.ok(!(await listVouchers({financeOnly:true})).some(v=>v.id===high.id));
  await assert.rejects(approveVoucher(high.id,"Finance",undefined,"HIGH"),/trader must approve/);
  await assert.rejects(resolveExcessAdvance(high.id,"Other trader",true),/Only the trade/);
  await resolveExcessAdvance(high.id,trader.name!,true);
  assert.ok((await listVouchers({financeOnly:true})).some(v=>v.id===high.id));
  await approveVoucher(high.id,"Finance",undefined,"HIGH");
  await assert.rejects(resolveExcessAdvance(high.id,trader.name!,true),/not awaiting/);
  console.log("PASS: excess advance trader ownership, finance bypass protection, approval routing");
  const repeated = await createVoucher({executionEntity:"PAK",commodityCode:"SES",counterpartyId:cp.id,side:"BUY",tradeRef:purchase.tradeRef,builtyNumber:"1001",truckNo:"OTHER-TRUCK",transporterName:"Carrier",advanceWeightKg:1000,advancePercentage:70,amountPkr:1000,enteredByName:"Execution"});
  assert.equal(repeated.advancePercentage,70); assert.equal(repeated.reference,null);
  await assert.rejects(createPendingTruck({counterpartyName:cp.name,movementType:"INBOUND",warehouseName:"Pakistan Store",truckNo:"OTHER-TRUCK",builtyDetails:"1001",commodityCode:"SES",commodityName:"Sesame",recordedByName:"Gate",weightKg:1000,warehouseWeightKg:1000}),/advance voucher/);
  await approveVoucher(repeated.id,"Finance",undefined,"REPEATED-1001");
  await assert.rejects(gate(repeated,"1001",1000),/unused approved/);
  await prisma.executionContract.update({where:{tradeRef:purchase.tradeRef},data:{executionProfile:"PURCHASE_SPOT"}});
  const spot=await createPendingTruck({counterpartyName:cp.name,movementType:"INBOUND",warehouseName:"Pakistan Store",truckNo:"SPOT",builtyDetails:"2000",commodityCode:"SES",commodityName:"Sesame",recordedByName:"Gate",weightKg:1000,weightAsPerBuiltyKg:1000,warehouseWeightKg:950});
  await assignTruckToTrade(spot.id,purchase.tradeRef);
  await prisma.trade.update({where:{tradeRef:purchase.tradeRef},data:{tradeStatus:"EXECUTED"}});
  const lab={truckId:spot.id,tradeRef:purchase.tradeRef,readings:{purity:"99",ffa:"2",moisture:"7",oilContent:"49",admixture:"1"},deductionKg:1};
  await assert.rejects(recordTruckQuality(lab,"Lab","SES","PAK"),/cannot have weight deductions/);
  await recordTruckQuality({...lab,deductionKg:0},"Lab","SES","PAK");
  const spotReceipt=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:spot.gatepassNo}});
  assert.equal(Number(spotReceipt.allocatedQtyMt),0.95);assert.equal(Number(spotReceipt.amountDue),1000*terms.rateKg);
  assert.equal(Number(spotReceipt.weightWarehouseKg),950);
  const wh=await prisma.location.create({data:{name:"Shared WH",country:"Pakistan",type:"WAREHOUSE",warehouseBasis:"LEASE",capacitySqFt:1000,grainDivisionSqFt:10,balesDivisionSqFt:5,createdById:admin.id}});
  for(const [code,qty] of [["SES",20],["CORN",30]] as const)await prisma.stockTransfer.create({data:{transferRef:`OPEN-${code}`,commodityCode:code,commodityName:code,externalOrigin:"Opening",toWarehouseName:wh.name,dispatchedQtyMt:qty,receivedQtyMt:qty,truckNo:"OPEN",status:"RECEIVED"}});
  const capacity=(await pak.trader.warehouseAvailability({commodityId:sesame.id})).warehouses.find(w=>w.id===wh.id)!;
  assert.equal(capacity.utilizationPct,50);assert.equal(capacity.stockMt,50);
  assert.deepEqual(capacity.commodityUtilization.map(c=>c.utilizationPct).sort(),[20,30]);
  console.log("PASS: repeat builty/different truck, truck mismatch blocked, finance references, spot seller weight, no spot deduction, shared corn/sesame capacity");

}
main().finally(()=>prisma.$disconnect());
