/** Integration check: an EMPTY, disposable local database on port 55433 only. */
import assert from "node:assert/strict";
import bcrypt from "bcryptjs";
import { prisma } from "../server/db";
import { appRouter } from "../server/routers/_app";
import { assignCommodityTrader } from "../server/commodity-assignments";
import { SESAME_DEFAULTS } from "../lib/sesame";
import { approveVoucher } from "../server/finance/vouchers";
import { canFundTruck } from "../server/finance/ledger";
import { pakistanAvailable } from "../server/execution/sesame-stock";

async function main() {
  const url = new URL(process.env.POSTGRES_PRISMA_URL ?? "http://invalid");
  assert.ok(["localhost", "127.0.0.1"].includes(url.hostname) && url.port === "55433");
  assert.equal(await prisma.user.count(), 0, "Only an empty disposable database is allowed");
  const passwordHash = await bcrypt.hash("LocalTest123!", 4);
  const admin = await prisma.user.create({ data: { email: "admin@example.test", name: "Admin", role: "CEO", passwordHash } });
  const employee = await prisma.user.create({ data: { email: "execution@example.test", name: "Execution Member", role: "EXECUTION", passwordHash } });
  const trader = await prisma.user.create({ data: { email: "trader@example.test", name: "Test Trader", role: "TRADER", passwordHash } });
  const sesame = await prisma.commodity.create({ data: { code: "SES", name: "Sesame", category: "OILSEEDS", unit: "MT", createdById: admin.id } });
  await prisma.commodity.create({ data: { code: "CORN", name: "Corn", category: "GRAINS", unit: "MT", createdById: admin.id } });
  const cp = await prisma.counterparty.create({ data: { code: "CP-TEST", name: "Test Counterparty", country: "Pakistan", type: "TRADING_PARTNER", createdById: admin.id } });
  await assignCommodityTrader({ commodityId: sesame.id, traderId: trader.id, expectedVersion: 0, actorId: admin.id });
  const caller = (user = employee, code?: string, entity?: "PAK" | "FZCO") => appRouter.createCaller({ prisma, executionCommodityCode: code, executionEntity: entity, session: { user: { id: user.id, name: user.name, email: user.email, role: user.role, isHead: user.isHead }, expires: "2099-01-01" } });
  const pak = caller(employee, "SES", "PAK"), dubai = caller(employee, "SES", "FZCO"), head = caller(admin, "SES", "PAK"), dh = caller(admin, "SES", "FZCO");
  const book = async (direction: "BUY" | "SELL", entity: "PAK" | "FZCO", quantity: number, internal?: "PAK" | "FZCO") => caller(trader).trader.bookTrade({
    traderName: trader.name!, commodityId: sesame.id, counterpartyId: cp.id, direction, quantity, quantityUnit: "MT", price: 1200, priceIncludesCommission: true, commissionPerUnit: 10, priceCurrency: "USD", priceWeightUnit: "MT", priceKgPerUnit: 1000, priceBasis: "Fixed", tradeDate: new Date(), deliveryStart: new Date(), deliveryEnd: new Date(), originName: "Karachi", incoterms: "Delivered", paymentType: "LC", tradeScope: "LOCAL", tradeParams: { ...SESAME_DEFAULTS, tradingEntity: entity === "FZCO" ? "Kastros FZCO" : "Kastros PAK", ...(internal ? { internalCounterpartyEntity: internal } : {}) }, submitToExecution: true,
  });
  await pak.trader.setPositionMarketInput({ commodityCode: "SES", season: "SUMMER", fxRate: 280, marketRatePkrPerMaund: 14000 });
  const purchase = await book("BUY", "PAK", 100);
  await head.execution.approveOpenTradeWarehouseSplit({ tradeRef: purchase.tradeRef, allocations: [{ warehouseName: "Pakistan Store", openQtyMt: 100 }] });
  await pak.execution.lockOpenTrade({ tradeRef: purchase.tradeRef });
  const inbound = await pak.execution.createPendingTruck({ counterpartyName: cp.name, movementType: "INBOUND", warehouseName: "Pakistan Store", truckNo: "PAK-IN", builtyDetails: "Test", commodityCode: "SES", commodityName: "Sesame", recordedByName: employee.name!, weightAsPerBuiltyKg: 100000, warehouseWeightKg: 100000, totalDeductionsKg: 0 });
  await pak.execution.assignTruckToTrade({ truckId: inbound.id, tradeRef: purchase.tradeRef });
  console.log("PASS: Pakistan physical receipt, 100 MT");
  const transfer = await book("BUY", "FZCO", 40, "PAK");
  await dubai.execution.lockOpenTrade({ tradeRef: transfer.tradeRef });
  const contract = (await dubai.execution.contractByRef({ tradeRef: transfer.tradeRef })).contract;
  assert.equal(contract.paperOwnership, true);
  assert.equal(contract.warehouseAllocations?.length ?? 0, 0);
  await assert.rejects(() => pak.sesameExecution.confirmOwnership({ tradeRef: transfer.tradeRef, quantityMt: 40, warehouseName: "Pakistan Store" }), /Head/);
  await assert.rejects(() => dh.sesameExecution.confirmOwnership({ tradeRef: transfer.tradeRef, quantityMt: 40, warehouseName: "Pakistan Store" }), /Pakistan/);
  await head.sesameExecution.confirmOwnership({ tradeRef: transfer.tradeRef, quantityMt: 40, warehouseName: "Pakistan Store" });
  let state = await pak.sesameExecution.book();
  assert.equal(state.positions[0].ownedMt, 60); assert.equal(state.positions[1].ownedMt, 40); assert.equal(state.positions[0].physicalInPakistanMt, 100);
  assert.ok((await dubai.sesameExecution.book()).trades.some(t => t.tradeRef === transfer.tradeRef && t.internalEntity === "PAK"));
  await assert.rejects(() => head.sesameExecution.confirmOwnership({ tradeRef: transfer.tradeRef, quantityMt: 1, warehouseName: "Pakistan Store" }));
  assert.equal(await pakistanAvailable(prisma, "SES", "Pakistan Store"), 60);
  await assert.rejects(() => pak.execution.createPendingTruck({ counterpartyName: cp.name, movementType: "OUTBOUND", warehouseName: "Pakistan Store", truckNo: "OVER", builtyDetails: "Test", commodityCode: "SES", commodityName: "Sesame", recordedByName: employee.name!, weightAsPerBuiltyKg: 61000 }), /Insufficient/);
  console.log("PASS: internal trade mirrored, ownership transferred, physical stock unchanged, Pakistan cannot use FZCO stock");
  const sale = await book("SELL", "FZCO", 15);
  await dubai.execution.lockOpenTrade({ tradeRef: sale.tradeRef });
  await assert.rejects(() => pak.sesameExecution.loadTruck({ tradeRef: sale.tradeRef, truckNo: "WRONG", transporterName: "Test", weightKg: 10000 }), /another commodity|Dubai/);
  const truck = await dubai.sesameExecution.loadTruck({ tradeRef: sale.tradeRef, truckNo: "FZCO-OUT", transporterName: "Test Transport", weightKg: 10000 });
  state = await pak.sesameExecution.book();
  assert.equal(state.positions[0].physicalInPakistanMt, 100); assert.equal(state.positions[1].ownedMt, 40); assert.equal(state.positions[1].loadingMt, 10);
  assert.ok(!(await pak.execution.pendingTrucks()).some(t => t.id === truck.truckId));
  assert.ok((await dubai.execution.pendingTrucks()).some(t => t.id === truck.truckId));
  await assert.rejects(() => dubai.sesameExecution.loadTruck({ tradeRef: sale.tradeRef, truckNo: "TOO-MUCH", transporterName: "Test", weightKg: 6000 }), /remaining sale/);
  const pCredit = await pak.execution.createVoucher({ counterpartyId: cp.id, amountPkr: 5000000, reference: "PAK-CREDIT", method: "Cash" }); await approveVoucher(pCredit.id, "Test Finance");
  assert.equal((await canFundTruck({ counterpartyId: cp.id, tradeRef: sale.tradeRef, amountPkr: 3332000, excludeTruckId: truck.truckId })).ok, false);
  const dCredit = await dubai.execution.createVoucher({ counterpartyId: cp.id, amountPkr: 4000000, reference: "FZCO-CREDIT", method: "Cash" }); await approveVoucher(dCredit.id, "Test Finance");
  assert.equal((await pak.execution.counterpartyLedgers({ entity: "PAK" })).find(a => a.side === "SELL")?.totalCreditPkr, 5000000);
  assert.equal((await pak.execution.counterpartyLedgers({ entity: "FZCO" })).find(a => a.side === "SELL")?.totalCreditPkr, 4000000);
  console.log("PASS: FZCO truck reservation and entity-isolated funding / central ledger");
  await dubai.execution.generateDeliveryOrder({ truckId: truck.truckId });
  await dh.execution.approveDoExecution({ truckId: truck.truckId });
  await caller(admin).execution.approveDoFinance({ truckId: truck.truckId });
  await dubai.execution.generateGatePass({ truckId: truck.truckId });
  await dubai.execution.markSaleReleased({ truckId: truck.truckId });
  state = await pak.sesameExecution.book();
  assert.equal(state.positions[0].physicalInPakistanMt, 90); assert.equal(state.positions[0].ownedMt, 60); assert.equal(state.positions[1].ownedMt, 30); assert.equal(state.positions[1].loadingMt, 0);
  await assert.rejects(() => dubai.execution.markSaleReleased({ truckId: truck.truckId }), /already/);
  console.log("PASS: full DO, execution + finance approvals, gate pass and release; physical=90 / PAK=60 / FZCO=30");
  const unused = await dubai.sesameExecution.loadTruck({ tradeRef: sale.tradeRef, truckNo: "CANCEL-LOAD", transporterName: "Test", weightKg: 5000 });
  await dh.sesameExecution.cancelLoad({ truckId: unused.truckId });
  assert.equal((await pak.sesameExecution.book()).positions[1].loadingMt, 0);
  const reverse = await book("BUY", "PAK", 5, "FZCO"); await pak.execution.lockOpenTrade({ tradeRef: reverse.tradeRef });
  await head.sesameExecution.confirmOwnership({ tradeRef: reverse.tradeRef, quantityMt: 5, warehouseName: "Pakistan Store" });
  state = await pak.sesameExecution.book(); assert.equal(state.positions[0].ownedMt, 65); assert.equal(state.positions[1].ownedMt, 25); assert.equal(state.positions[0].physicalInPakistanMt, 90);
  const external = await book("BUY", "FZCO", 2); await dubai.execution.lockOpenTrade({ tradeRef: external.tradeRef });
  await dh.sesameExecution.confirmOwnership({ tradeRef: external.tradeRef, quantityMt: 2 });
  state = await pak.sesameExecution.book(); assert.equal(state.positions[1].ownedMt, 27); assert.equal(state.positions[0].physicalInPakistanMt, 90);
  const notes = await dubai.execution.openSettlementNotes({ counterpartyId: cp.id, side: "BUY" });
  assert.ok(notes.some(n => n.tradeRef === external.tradeRef && n.noteRef.startsWith("OWN-")));
  const note = notes.find(n => n.tradeRef === external.tradeRef)!;
  const payment = await dubai.execution.createVoucher({ counterpartyId: cp.id, side: "BUY", noteRef: note.noteRef, amountPkr: note.amountPkr, method: "Cash", reference: "FZCO-PURCHASE-PAY" });
  await approveVoucher(payment.id, "Test Finance");
  assert.ok(!(await dubai.execution.openSettlementNotes({ counterpartyId: cp.id, side: "BUY" })).some(n => n.noteRef === note.noteRef));
  const csv = (await dubai.execution.exportTradeFileCsv({})).csv;
  assert.ok(csv.includes(sale.tradeRef) && !csv.includes(purchase.tradeRef));
  assert.equal((await caller(employee, "CORN").execution.pendingTrucks()).length, 0);
  console.log("PASS: load cancellation, reverse ownership, external paper purchases and payable settlement, exports, Corn isolation");
}
main().finally(() => prisma.$disconnect()).catch(error => { console.error(error); process.exitCode = 1; });
