/** Integration check: an EMPTY, disposable local database on port 55433 only. */
import assert from "node:assert/strict";
import bcrypt from "bcryptjs";
import { prisma } from "../server/db";
import { appRouter } from "../server/routers/_app";
import { assignCommodityTrader } from "../server/commodity-assignments";
import { SESAME_DEFAULTS } from "../lib/sesame";
import { createVoucher, listVouchers, approveVoucher } from "../server/finance/vouchers";
import { canFundTruck } from "../server/finance/ledger";
import { pakistanAvailable } from "../server/execution/sesame-stock";

import { createPendingTruck, assignTruckToTrade, setManualGateInvoice, traderResolveGateInvoice } from "../server/execution/trucks";
import { approvePayment } from "../server/execution/payments";
import { applyAdvance, advanceTrade } from "../server/finance/purchase-advances";
import { getCounterpartyLedgers } from "../server/finance/ledger";
import { advanceAmount } from "../lib/purchase-advance";
async function main() {
  const url = new URL(process.env.POSTGRES_PRISMA_URL ?? "http://invalid");
  assert.ok(["localhost", "127.0.0.1"].includes(url.hostname) && url.port === "55433");
  assert.equal(await prisma.user.count(), 0, "Only an empty disposable database is allowed");
  const passwordHash = await bcrypt.hash("LocalTest123!", 4);
  const admin = await prisma.user.create({ data: { email: "admin@example.test", name: "Admin", role: "CEO", passwordHash } });
  const employee = await prisma.user.create({ data: { email: "execution@example.test", name: "Execution Member", role: "EXECUTION", passwordHash } });
  const trader = await prisma.user.create({ data: { email: "trader@example.test", name: "Test Trader", role: "TRADER", passwordHash } });
  const sesame = await prisma.commodity.create({ data: { code: "SES", name: "Sesame", category: "OILSEEDS", unit: "MT", createdById: admin.id } });
  await prisma.commodity.create({ data: { code: "CORN", name: "Corn", category: "GRAINS", unit: "MT", createdById: admin.id } });
  const cp = await prisma.counterparty.create({ data: { code: "CP-TEST", name: "Test Counterparty", country: "Pakistan", type: "TRADING_PARTNER", createdById: admin.id } });
  await assignCommodityTrader({ commodityId: sesame.id, traderId: trader.id, expectedVersion: 0, actorId: admin.id });
  const caller = (user = employee, code?: string, entity?: "PAK" | "FZCO") => appRouter.createCaller({ prisma, executionCommodityCode: code, executionEntity: entity, session: { user: { id: user.id, name: user.name, email: user.email, role: user.role, isHead: user.isHead }, expires: "2099-01-01" } });
  const pak = caller(employee, "SES", "PAK"), dubai = caller(employee, "SES", "FZCO"), head = caller(admin, "SES", "PAK"), dh = caller(admin, "SES", "FZCO");
  const book = async (direction: "BUY" | "SELL", entity: "PAK" | "FZCO", quantity: number, internal?: "PAK" | "FZCO") => caller(trader).trader.bookTrade({
    traderName: trader.name!, commodityId: sesame.id, counterpartyId: cp.id, direction, quantity, quantityUnit: "MT", price: 1200, priceIncludesCommission: true, commissionPerUnit: 10, priceCurrency: "USD", priceWeightUnit: "MT", priceKgPerUnit: 1000, priceBasis: "Fixed", tradeDate: new Date(), deliveryStart: new Date(), deliveryEnd: new Date(), originName: "Karachi", incoterms: "Delivered", paymentType: "ADVANCE_100", tradeScope: "LOCAL", tradeParams: { ...SESAME_DEFAULTS, paymentPercentage: 80, tradingEntity: entity === "FZCO" ? "Kastros FZCO" : "Kastros PAK", ...(internal ? { internalCounterpartyEntity: internal } : {}) }, submitToExecution: true,
  });
  await pak.trader.setPositionMarketInput({ commodityCode: "SES", season: "SUMMER", fxRate: 280, marketRatePkrPerMaund: 14000 });
  const purchase = await book("BUY", "PAK", 100);
  await head.execution.approveOpenTradeWarehouseSplit({ tradeRef: purchase.tradeRef, allocations: [{ warehouseName: "Pakistan Store", openQtyMt: 100 }] });
  await pak.execution.lockOpenTrade({ tradeRef: purchase.tradeRef });
  const terms = await advanceTrade(purchase.tradeRef);
  const voucher = async (builty: string, amount: number, weight = 40000) => createVoucher({ executionEntity: "PAK", commodityCode: "SES", counterpartyId: cp.id, side: "BUY", tradeRef: purchase.tradeRef, builtyNumber: builty, transporterName: "Test Transport", advanceWeightKg: weight, amountPkr: amount, reference: `BANK-${builty}`, method: "Cash", enteredByName: "Execution" });
  const gate = async (v: Awaited<ReturnType<typeof voucher>>, builty: string, received: number) => createPendingTruck({ counterpartyName: cp.name, movementType: "INBOUND", warehouseName: "Pakistan Store", truckNo: `TRUCK-${builty}`, builtyDetails: builty, commodityCode: "SES", commodityName: "Sesame", recordedByName: "Gate", weightKg: received, warehouseWeightKg: received, advanceVoucherId: v.id, advanceTradeRef: purchase.tradeRef });
  const first = await voucher("1001", advanceAmount(40000, terms.rateKg, 80));
  assert.equal(first.advancePercentage,80); assert.equal(first.calculatedAdvancePkr,first.amountPkr);
  await assert.rejects(gate(first,"1001",35000),/unused approved/);
  await approveVoucher(first.id,"Finance");
  await assert.rejects(approveVoucher(first.id,"Finance"),/already resolved/);
  await assert.rejects(voucher("1001",500),/active advance/);
  const truck=await gate(first,"1001",35000);
  await assert.rejects(gate(first,"1001",35000),/unused approved/);
  await assignTruckToTrade(truck.id,purchase.tradeRef,undefined,false,1000);
  const receipt=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:truck.gatepassNo}});
  assert.equal(Number(receipt.allocatedQtyMt),34);
  assert.equal(Number(receipt.amountDue),34000*terms.rateKg);
  await setManualGateInvoice(truck.id,{invoiceNo:"INV-1001",amountPkr:Number(receipt.amountDue)});
  await traderResolveGateInvoice(trader.name!,truck.id,"APPROVE");
  const payment=await prisma.paymentRequest.findFirstOrThrow({where:{sourceId:receipt.id,status:"PENDING"}});
  assert.equal(Number(payment.amount),Number(receipt.amountDue)-first.amountPkr);
  assert.equal(payment.builtyNumber,"1001");assert.equal(payment.invoiceNumber,"INV-1001");assert.equal(Number(payment.remainingPercentage),20);
  await approvePayment(payment.requestRef,"Finance");
  await assert.rejects(approvePayment(payment.requestRef,"Finance"),/Cannot approve/);
  const settled=(await listVouchers()).find(v=>v.id===first.id)!;
  assert.equal(settled.truckPaid,true);assert.equal(settled.availableAdvancePkr,0);
  const ledger=(await getCounterpartyLedgers("SES","PAK")).find(a=>a.counterpartyId===cp.id&&a.side==="BUY")!;
  assert.equal(ledger.totalCreditPkr,Number(receipt.amountDue));assert.equal(ledger.balancePkr,0);
  assert.equal(ledger.entries.filter(e=>e.entryType==="CREDIT").length,2);
  console.log("PASS: advance, short receipt, deduction, remaining finance payment, ledger credits, paid badge, retries");
  await prisma.trade.update({ where: { tradeRef: purchase.tradeRef }, data: { tradeParams: { ...SESAME_DEFAULTS, tradingEntity: "Kastros PAK", paymentPercentage: 90 } } });
  const over=await voucher("1002",10000,40);
  assert.equal(over.advancePercentage,90);
  assert.equal((await listVouchers()).find(v => v.id === first.id)!.advancePercentage,80);
  assert.notEqual(over.amountPkr,over.calculatedAdvancePkr);
  await approveVoucher(over.id,"Finance");
  const short=await gate(over,"1002",35);
  await assignTruckToTrade(short.id,purchase.tradeRef,undefined,false,5);
  const shortReceipt=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:short.gatepassNo}});
  await setManualGateInvoice(short.id,{invoiceNo:"INV-1002",amountPkr:Number(shortReceipt.amountDue)});
  await traderResolveGateInvoice(trader.name!,short.id,"APPROVE");
  const excess=(await listVouchers()).find(v=>v.id===over.id)!;
  assert.equal(excess.truckPaid,true);assert.ok(excess.availableAdvancePkr>0);
  assert.equal(await prisma.paymentRequest.count({where:{sourceId:shortReceipt.id}}),0);
  const next=await createPendingTruck({counterpartyName:cp.name,movementType:"INBOUND",warehouseName:"Pakistan Store",truckNo:"FUTURE",builtyDetails:"1003",commodityCode:"SES",commodityName:"Sesame",recordedByName:"Gate",weightKg:1000,warehouseWeightKg:1000});
  await assignTruckToTrade(next.id,purchase.tradeRef);
  const nextReceipt=await prisma.inboundReceipt.findFirstOrThrow({where:{gatepassNo:next.gatepassNo}});
  await setManualGateInvoice(next.id,{invoiceNo:"INV-1003",amountPkr:Number(nextReceipt.amountDue)});
  await assert.rejects(prisma.$transaction(tx=>applyAdvance(tx,over.id,next.id,"Execution",excess.availableAdvancePkr+1)),/exceeds/);
  await assert.rejects(prisma.$transaction(async tx => {
    await tx.trade.update({ where: { tradeRef: purchase.tradeRef }, data: { tradeParams: { ...SESAME_DEFAULTS, tradingEntity: "Kastros FZCO" } } });
    await applyAdvance(tx,over.id,next.id,"Execution",1);
  }), /same supplier, commodity and entity/);
  await prisma.$transaction(tx=>applyAdvance(tx,over.id,next.id,"Execution",excess.availableAdvancePkr));
  await assert.rejects(prisma.$transaction(tx=>applyAdvance(tx,over.id,next.id,"Execution",1)),/exceeds/);
  assert.equal((await listVouchers()).find(v=>v.id===over.id)!.availableAdvancePkr,0);
  await traderResolveGateInvoice(trader.name!,next.id,"APPROVE");
  const nextPayment=await prisma.paymentRequest.findFirstOrThrow({where:{sourceId:nextReceipt.id,status:"PENDING"}});
  await approvePayment(nextPayment.requestRef,"Finance");
  const finalLedger=(await getCounterpartyLedgers("SES","PAK")).find(a=>a.counterpartyId===cp.id&&a.side==="BUY")!;
  assert.equal(finalLedger.balancePkr,0);assert.equal(finalLedger.outstandingDebitPkr,0);
  console.log("PASS: manual override, excess credit, future truck allocation, overspend protection, no duplicate credit");
}
main().finally(()=>prisma.$disconnect());
